import { execSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));

let commit = 'unknown';
try {
  commit = execSync('git rev-parse --short HEAD', { cwd: root }).toString().trim();
} catch {
  // not a git checkout (e.g. release tarball); fall back to 'unknown'
}

const out = `// Generated by scripts/generate-version.mjs — do not edit.
export const VIEWER_VERSION = '${pkg.version}';
export const VIEWER_COMMIT = '${commit}';
`;

const dest = join(root, 'src', 'generated', 'version.ts');
mkdirSync(dirname(dest), { recursive: true });
writeFileSync(dest, out);
console.log(`generated version.ts (v${pkg.version}, commit ${commit})`);
